/**
 * Semantic vector store for skills — two-layer approach:
 *
 *  Layer 1 (always, offline): TF-IDF sparse vectors stored as JSON.
 *    Cosine similarity computed in JS against all stored vectors.
 *
 *  Layer 2 (optional, when ANTHROPIC_API_KEY is set):
 *    40-dim capability vector generated by Claude Haiku once per skill
 *    (~100 tokens each, never called at search time).
 *    Query is mapped to the same 40 dims via keyword matching — no API call.
 *
 *  Combined score = 0.65 × TF-IDF + 0.35 × capability-space cosine
 *
 * No external model download required. sqlite-vec is loaded for future
 * dense-embedding migrations but is not used for queries yet.
 */

import Database from 'better-sqlite3'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const VECTOR_DB_PATH = process.env.VECTOR_DB_PATH
  ?? (process.env.VERCEL ? '/tmp/skills_vectors.db' : join(__dirname, '..', '..', 'skills_vectors.db'))

export const vectorDb = new Database(VECTOR_DB_PATH)
vectorDb.pragma('journal_mode = WAL')

// ─── Schema ───────────────────────────────────────────────────────────────────

export function initVectorDb() {
  vectorDb.exec(`
    CREATE TABLE IF NOT EXISTS skill_embeddings (
      skill_id    INTEGER PRIMARY KEY,
      tfidf_vec   TEXT NOT NULL DEFAULT '{}',
      cap_vec     TEXT,
      text_snip   TEXT,
      embedded_at TEXT DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS corpus_vocab (
      term     TEXT    PRIMARY KEY,
      doc_freq INTEGER NOT NULL DEFAULT 1
    );

    CREATE TABLE IF NOT EXISTS corpus_meta (
      key   TEXT PRIMARY KEY,
      value TEXT
    );
  `)
}

// ─── 40-dim capability space ──────────────────────────────────────────────────
// Fixed shared vocabulary between indexing (Claude) and search (keyword match).

export const CAPABILITY_DIMS = [
  'code-generation', 'code-review', 'refactoring', 'testing', 'debugging',
  'web-search', 'web-scraping', 'browser-automation', 'html-parsing', 'http-api',
  'github', 'git', 'version-control', 'pull-requests', 'issue-tracking',
  'filesystem', 'read-files', 'write-files', 'local-storage',
  'database', 'sql', 'nosql', 'data-persistence',
  'documentation', 'markdown', 'readme',
  'chat', 'conversation', 'ai-assistant', 'llm',
  'terminal', 'cli', 'command-line', 'shell',
  'authentication', 'security', 'encryption',
  'deployment', 'devops', 'containerization',
  'mcp-server', 'model-context-protocol',
]

// ─── Stopwords ────────────────────────────────────────────────────────────────

const STOP = new Set([
  'the', 'and', 'for', 'with', 'that', 'this', 'are', 'from', 'your', 'you',
  'can', 'has', 'was', 'all', 'any', 'but', 'not', 'its', 'via', 'use', 'get',
  'set', 'new', 'add', 'our', 'will', 'which', 'have', 'been', 'into', 'more',
  'also', 'used', 'such', 'like', 'each', 'than', 'then', 'when', 'what',
  'how', 'make', 'both', 'need', 'even', 'just', 'tool', 'allows', 'provide',
  'using', 'based', 'built', 'support', 'provides', 'enables', 'works', 'lets',
])

// ─── Text helpers ─────────────────────────────────────────────────────────────

function extractTermFreqs(text) {
  const freq = {}
  text
    .toLowerCase()
    .replace(/[^\w\s\-]/g, ' ')
    .split(/[\s_/]+/)
    .flatMap(t => t.split('-'))
    .filter(t => t.length >= 3 && t.length <= 30 && !STOP.has(t))
    .forEach(t => { freq[t] = (freq[t] || 0) + 1 })
  return freq
}

function buildSnippet(skill, tags = []) {
  const parts = [skill.name, skill.description || '', skill.category || '']
  let feats = []
  try { feats = JSON.parse(skill.features || '[]') } catch {}
  if (feats.length) parts.push(feats.slice(0, 5).join(' '))
  if (tags.length)  parts.push(tags.join(' '))
  return parts.filter(Boolean).join(' ').slice(0, 1000)
}

// ─── Corpus helpers ───────────────────────────────────────────────────────────

function getDocCount() {
  const r = vectorDb.prepare("SELECT value FROM corpus_meta WHERE key='doc_count'").get()
  return r ? parseInt(r.value, 10) : 0
}

function incrementDocCount() {
  vectorDb.prepare(`
    INSERT INTO corpus_meta (key, value) VALUES ('doc_count', '1')
    ON CONFLICT(key) DO UPDATE SET value = CAST(CAST(value AS INTEGER) + 1 AS TEXT)
  `).run()
}

function updateVocab(termFreqs) {
  const stmt = vectorDb.prepare(`
    INSERT INTO corpus_vocab (term, doc_freq) VALUES (?, 1)
    ON CONFLICT(term) DO UPDATE SET doc_freq = doc_freq + 1
  `)
  const tx = vectorDb.transaction(() => {
    for (const t of Object.keys(termFreqs)) stmt.run(t)
  })
  tx()
}

function computeTfIdf(termFreqs, docCount) {
  const total = Object.values(termFreqs).reduce((s, n) => s + n, 0)
  if (!total) return {}
  const vec = {}
  for (const [term, tf] of Object.entries(termFreqs)) {
    const df = vectorDb.prepare('SELECT doc_freq FROM corpus_vocab WHERE term=?').get(term)?.doc_freq || 1
    const idf = Math.log((docCount + 1) / (df + 1)) + 1
    const score = (tf / total) * idf
    if (score > 0.01) vec[term] = parseFloat(score.toFixed(4))
  }
  return vec
}

// ─── Capability vector ────────────────────────────────────────────────────────

// Fast offline approximation: score each dim by keyword overlap with text.
function keywordCapVec(text) {
  const t = text.toLowerCase()
  return CAPABILITY_DIMS.map(dim => {
    const keywords = dim.split('-')
    const hits = keywords.filter(kw => t.includes(kw)).length
    return parseFloat((hits / keywords.length).toFixed(3))
  })
}

// Claude Haiku call — one-time cost at indexing, never at search time.
async function claudeCapVec(snip) {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return null
  try {
    const { default: Anthropic } = await import('@anthropic-ai/sdk')
    const client = new Anthropic({ apiKey })
    const n = CAPABILITY_DIMS.length
    const msg = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 120,
      messages: [{
        role: 'user',
        content: `Score this AI tool on ${n} dimensions (0.0–1.0 each).\nTool: "${snip.slice(0, 250)}"\nDimensions: ${CAPABILITY_DIMS.join(', ')}\nReturn ONLY a JSON array of ${n} floats. No explanation.`,
      }],
    })
    const arr = JSON.parse(msg.content[0].text.trim())
    if (Array.isArray(arr) && arr.length === n)
      return arr.map(v => parseFloat(parseFloat(v).toFixed(3)))
  } catch {}
  return null
}

// ─── Similarity ───────────────────────────────────────────────────────────────

function sparseCosine(a, b) {
  let dot = 0, normA = 0, normB = 0
  for (const [t, w] of Object.entries(a)) {
    normA += w * w
    if (b[t] !== undefined) dot += w * b[t]
  }
  for (const w of Object.values(b)) normB += w * w
  const denom = Math.sqrt(normA * normB)
  return denom ? dot / denom : 0
}

function denseCosine(a, b) {
  let dot = 0, nA = 0, nB = 0
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]; nA += a[i] * a[i]; nB += b[i] * b[i]
  }
  const denom = Math.sqrt(nA * nB)
  return denom ? dot / denom : 0
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Embed a skill and persist. Called by scraper on every new skill.
 * Layer-2 (Claude) is fire-and-forget: a failure doesn't break scraping.
 */
export async function upsertSkillVector(skillId, skill, tags = []) {
  const snip = buildSnippet(skill, tags)
  const termFreqs = extractTermFreqs(snip)

  updateVocab(termFreqs)
  incrementDocCount()
  const docCount = getDocCount()
  const tfidf = computeTfIdf(termFreqs, docCount)

  const capVec = await claudeCapVec(snip)   // null when no API key

  vectorDb.prepare(
    'INSERT OR REPLACE INTO skill_embeddings (skill_id, tfidf_vec, cap_vec, text_snip) VALUES (?, ?, ?, ?)'
  ).run(skillId, JSON.stringify(tfidf), capVec ? JSON.stringify(capVec) : null, snip.slice(0, 300))
}

/**
 * Return top-k skills matching `query` semantically.
 * Zero API calls at search time — only local computation.
 * Returns [{skill_id, score, tfidf_score, cap_score}]
 */
export function semanticSearch(query, topK = 10) {
  const rows = vectorDb.prepare(
    'SELECT skill_id, tfidf_vec, cap_vec, text_snip FROM skill_embeddings'
  ).all()
  if (!rows.length) return []

  const docCount = getDocCount()
  const qTermFreqs = extractTermFreqs(query)
  const qTfidf = computeTfIdf(qTermFreqs, docCount || 1)
  const qCap = keywordCapVec(query)          // fast offline capability match

  const scored = rows.map(r => {
    const tfidf = JSON.parse(r.tfidf_vec || '{}')
    const tfidfScore = sparseCosine(qTfidf, tfidf)

    let capScore = 0
    if (r.cap_vec) {
      // If skill has Claude cap vector, blend Claude (indexed) × keyword (query)
      const cap = JSON.parse(r.cap_vec)
      capScore = denseCosine(qCap, cap)
    } else {
      // Fallback: keyword cap vec for both sides
      // We'd need to store a keyword cap vec at index time — use text_snip
      // to derive it now (cheap, no API)
      const skillCap = keywordCapVec(r.text_snip || '')
      capScore = denseCosine(qCap, skillCap)
    }

    const score = 0.65 * tfidfScore + 0.35 * capScore
    return { skill_id: r.skill_id, score, tfidf_score: tfidfScore, cap_score: capScore }
  })

  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, topK)
}

/**
 * Back-fill missing embeddings for skills already in `mainDb`.
 * Safe to call in background; non-blocking.
 */
export async function syncMissingVectors(mainDb) {
  // skill_embeddings lives in vectorDb, not mainDb — fetch existing IDs first
  const indexed = new Set(
    vectorDb.prepare('SELECT skill_id FROM skill_embeddings').all().map(r => r.skill_id)
  )

  const all = mainDb.prepare(`
    SELECT s.id, s.name, s.description, s.category, s.features,
           GROUP_CONCAT(t.name) AS tags
    FROM   skills s
    LEFT   JOIN skill_tags st ON st.skill_id = s.id
    LEFT   JOIN tags t        ON t.id = st.tag_id
    WHERE  s.is_active = 1
    GROUP  BY s.id
    LIMIT  500
  `).all()

  const missing = all.filter(r => !indexed.has(r.id))

  let count = 0
  for (const row of missing) {
    const tags = row.tags ? row.tags.split(',') : []
    await upsertSkillVector(row.id, row, tags)
    count++
  }
  return count
}
