from typing import List, Dict, Any
from .base import BaseScraper


class MCPServersScraper(BaseScraper):
    """Scraper for MCP (Model Context Protocol) servers."""

    async def scrape(self) -> List[Dict[str, Any]]:
        return [
            {
                "name": "filesystem MCP",
                "description": "MCP server for local filesystem access. Allows Claude to read, write, and manage files and directories on your local machine with configurable permissions.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "Read/write files",
                    "Directory listing",
                    "File search",
                    "Configurable root paths",
                    "Permission controls"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-filesystem\nAdd to claude_desktop_config.json:\n{"mcpServers": {"filesystem": {"command": "mcp-server-filesystem", "args": ["/your/path"]}}}',
                "popularity_score": 9.0,
                "tags": ["mcp", "filesystem", "file-management", "local", "official"],
            },
            {
                "name": "github MCP",
                "description": "MCP server for GitHub integration. Enables Claude to interact with GitHub repositories, issues, pull requests, and more through the GitHub API.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "Repository management",
                    "Issues and PRs",
                    "Code search",
                    "File contents",
                    "Branch management",
                    "Commit history"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-github\nRequires GITHUB_PERSONAL_ACCESS_TOKEN env var.',
                "popularity_score": 9.2,
                "tags": ["mcp", "github", "git", "version-control", "official", "devops"],
            },
            {
                "name": "postgres MCP",
                "description": "MCP server for PostgreSQL database access. Allows Claude to query, inspect schemas, and interact with PostgreSQL databases safely.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "SQL query execution",
                    "Schema inspection",
                    "Table listing",
                    "Read-only mode support",
                    "Connection pooling"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-postgres\nRequires PostgreSQL connection string.',
                "popularity_score": 8.5,
                "tags": ["mcp", "database", "postgresql", "sql", "official", "data"],
            },
            {
                "name": "puppeteer MCP",
                "description": "MCP server that provides browser automation via Puppeteer. Enables web scraping, screenshot capture, form filling, and automated browser interactions.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "Web page navigation",
                    "Screenshot capture",
                    "Form automation",
                    "JavaScript execution",
                    "Web scraping",
                    "Click and type simulation"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-puppeteer',
                "popularity_score": 8.8,
                "tags": ["mcp", "browser", "automation", "scraping", "official", "puppeteer"],
            },
            {
                "name": "brave-search MCP",
                "description": "MCP server for Brave Search API integration. Provides web search capabilities using Brave's privacy-focused search engine with rich result metadata.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
                "source_name": "MCP Official",
                "pricing": "freemium",
                "price_details": "Free tier: 2000 queries/month. Paid plans available.",
                "features": [
                    "Web search",
                    "News search",
                    "Privacy-focused results",
                    "Rich metadata",
                    "Image search"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-brave-search\nRequires BRAVE_API_KEY env var.',
                "popularity_score": 8.7,
                "tags": ["mcp", "search", "brave", "web-search", "official", "privacy"],
            },
            {
                "name": "fetch MCP",
                "description": "MCP server for HTTP fetching. Allows Claude to fetch web pages, APIs, and resources with full request/response control including headers and auth.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "HTTP/HTTPS requests",
                    "Custom headers",
                    "Authentication support",
                    "JSON parsing",
                    "HTML content extraction",
                    "Robots.txt compliance"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-fetch',
                "popularity_score": 9.1,
                "tags": ["mcp", "http", "web", "api", "official", "networking"],
            },
            {
                "name": "memory MCP",
                "description": "MCP server providing persistent memory via a knowledge graph. Allows Claude to store, retrieve, and reason over facts across conversations using an entity-relation model.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "Persistent knowledge graph",
                    "Entity creation and linking",
                    "Relation management",
                    "Cross-session memory",
                    "Observation storage",
                    "Graph queries"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-memory',
                "popularity_score": 8.6,
                "tags": ["mcp", "memory", "knowledge-graph", "persistence", "official", "ai"],
            },
            {
                "name": "everything MCP",
                "description": "A reference MCP server that demonstrates all MCP features including resources, tools, prompts, and sampling. Great for testing MCP integrations and learning the protocol.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "All MCP primitives",
                    "Resource demonstration",
                    "Tool examples",
                    "Prompt templates",
                    "Sampling reference",
                    "Testing utility"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-everything',
                "popularity_score": 6.5,
                "tags": ["mcp", "reference", "testing", "official", "development"],
            },
            {
                "name": "sequential-thinking MCP",
                "description": "MCP server that enables dynamic and reflective problem-solving through sequential thought chains. Helps Claude break complex problems into step-by-step reasoning processes.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "Step-by-step reasoning",
                    "Thought revision support",
                    "Branching reasoning",
                    "Problem decomposition",
                    "Chain-of-thought enhancement"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-sequentialthinking',
                "popularity_score": 8.2,
                "tags": ["mcp", "reasoning", "chain-of-thought", "official", "ai", "thinking"],
            },
            {
                "name": "slack MCP",
                "description": "MCP server for Slack integration. Allows Claude to read channels, post messages, search messages, and interact with Slack workspaces through the Slack API.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
                "source_name": "MCP Official",
                "pricing": "free",
                "features": [
                    "Channel reading",
                    "Message posting",
                    "Message search",
                    "User listing",
                    "Thread replies",
                    "File sharing"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-slack\nRequires SLACK_BOT_TOKEN and SLACK_TEAM_ID.',
                "popularity_score": 8.0,
                "tags": ["mcp", "slack", "messaging", "communication", "official", "workspace"],
            },
            {
                "name": "google-maps MCP",
                "description": "MCP server for Google Maps integration. Provides geocoding, place search, directions, and mapping capabilities through the Google Maps Platform API.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps",
                "source_name": "MCP Official",
                "pricing": "freemium",
                "price_details": "Requires Google Maps API key. Free tier available.",
                "features": [
                    "Geocoding",
                    "Place search",
                    "Directions",
                    "Distance matrix",
                    "Elevation data",
                    "Time zone info"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-google-maps\nRequires GOOGLE_MAPS_API_KEY env var.',
                "popularity_score": 7.5,
                "tags": ["mcp", "maps", "geocoding", "location", "official", "google"],
            },
            {
                "name": "aws-kb-retrieval MCP",
                "description": "MCP server for AWS Knowledge Base retrieval using Bedrock Agent Runtime. Enables RAG-powered document retrieval from AWS Bedrock Knowledge Bases.",
                "category": "MCP Server",
                "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/aws-kb-retrieval-server",
                "source_name": "MCP Official",
                "pricing": "paid",
                "price_details": "Requires AWS account. Pay-per-use via AWS Bedrock pricing.",
                "features": [
                    "RAG retrieval",
                    "AWS Bedrock integration",
                    "Knowledge base querying",
                    "Semantic search",
                    "Document chunking"
                ],
                "install_instructions": 'npm install -g @modelcontextprotocol/server-aws-kb-retrieval\nRequires AWS credentials and Knowledge Base ID.',
                "popularity_score": 7.0,
                "tags": ["mcp", "aws", "rag", "knowledge-base", "official", "bedrock", "retrieval"],
            },
        ]
