import json
from datetime import datetime
import aiosqlite


SEED_SKILLS = [
    # === Claude Code Built-in Skills ===
    {
        "name": "deep-research",
        "description": "Deep research harness that fans out web searches, fetches sources, adversarially verifies claims, and synthesizes a cited report. Perfect for multi-source fact-checked research on any topic.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Multi-source web search", "Adversarial claim verification", "Cited report synthesis", "Parallel search fan-out", "Source credibility assessment"]),
        "install_instructions": "Available as a built-in Claude Code skill. Invoke with /deep-research",
        "popularity_score": 9.5,
        "tags": ["research", "claude-code", "web-search", "analysis", "citations"],
    },
    {
        "name": "verify",
        "description": "Verify that a code change actually works by running the app and observing behavior. Use to verify PRs, confirm fixes, test changes manually, or validate local changes before pushing.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Automated behavior verification", "PR verification", "Manual test execution", "Visual output observation", "Pre-push validation"]),
        "install_instructions": "Available as a built-in Claude Code skill. Invoke with /verify",
        "popularity_score": 9.0,
        "tags": ["testing", "claude-code", "verification", "qa", "automation"],
    },
    {
        "name": "code-review",
        "description": "Review current diff for correctness bugs and reuse/simplification/efficiency cleanups at configurable effort levels. Can post findings as inline PR comments or apply fixes directly.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Multi-level effort modes", "Bug detection", "Efficiency analysis", "Inline PR comments (--comment)", "Auto-fix mode (--fix)", "Correctness checks"]),
        "install_instructions": "Built-in skill. Use /code-review, /code-review --comment, or /code-review --fix",
        "popularity_score": 9.8,
        "tags": ["code-review", "claude-code", "bugs", "quality", "pr", "automation"],
    },
    {
        "name": "simplify",
        "description": "Review changed code for reuse, simplification, efficiency, and altitude cleanups, then apply the fixes automatically. Focuses on quality improvements rather than bug hunting.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Code simplification", "Reuse detection", "Efficiency improvements", "Auto-apply fixes", "Altitude-aware refactoring"]),
        "install_instructions": "Built-in skill. Invoke with /simplify",
        "popularity_score": 8.5,
        "tags": ["refactoring", "claude-code", "simplification", "quality", "cleanup"],
    },
    {
        "name": "run",
        "description": "Launch and drive the project's app to see a change working. Use to run, start, or screenshot the app, or confirm a change works in the real app (not just tests).",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["App launch automation", "Screenshot capture", "Multi-project-type support", "Real-time behavior observation", "Change validation"]),
        "install_instructions": "Built-in skill. Invoke with /run",
        "popularity_score": 8.7,
        "tags": ["execution", "claude-code", "testing", "automation", "screenshots"],
    },
    {
        "name": "init",
        "description": "Initialize a new CLAUDE.md file with comprehensive codebase documentation. Analyzes the project and generates structured documentation for Claude Code sessions.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["CLAUDE.md generation", "Codebase analysis", "Project structure documentation", "Tech stack detection", "Auto-documentation"]),
        "install_instructions": "Built-in skill. Invoke with /init",
        "popularity_score": 8.0,
        "tags": ["documentation", "claude-code", "initialization", "setup"],
    },
    {
        "name": "review",
        "description": "Review a pull request comprehensively. Analyzes the PR diff, checks for bugs, logic issues, style violations, and provides structured feedback.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["PR diff analysis", "Bug identification", "Logic verification", "Style checking", "Structured feedback"]),
        "install_instructions": "Built-in skill. Invoke with /review",
        "popularity_score": 9.0,
        "tags": ["pr-review", "claude-code", "code-quality", "github"],
    },
    {
        "name": "security-review",
        "description": "Complete security review of pending changes on the current branch. Identifies vulnerabilities, injection risks, authentication issues, and security anti-patterns.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Vulnerability detection", "Injection risk analysis", "Auth/authz review", "Security anti-pattern detection", "Dependency risk assessment"]),
        "install_instructions": "Built-in skill. Invoke with /security-review",
        "popularity_score": 9.3,
        "tags": ["security", "claude-code", "vulnerabilities", "owasp", "audit"],
    },
    {
        "name": "update-config",
        "description": "Configure the Claude Code harness via settings.json. Set up automated behaviors, hooks, permissions, and environment variables. Essential for customizing Claude Code workflows.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Automated behavior configuration", "Hook setup", "Permission management", "Environment variable setting", "settings.json editing"]),
        "install_instructions": "Built-in skill. Invoke with /update-config",
        "popularity_score": 7.5,
        "tags": ["configuration", "claude-code", "hooks", "settings", "automation"],
    },
    {
        "name": "session-start-hook",
        "description": "Create and develop startup hooks for Claude Code on the web. Sets up a SessionStart hook to ensure the project can run tests and linters during web sessions.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Session initialization", "Test runner setup", "Linter configuration", "Web session support", "Auto-environment setup"]),
        "install_instructions": "Built-in skill. Invoke with /session-start-hook",
        "popularity_score": 7.0,
        "tags": ["hooks", "claude-code", "session", "testing", "automation"],
    },
    {
        "name": "claude-api",
        "description": "Build, debug, and optimize Claude API and Anthropic SDK applications. Handles prompt caching, model migrations, tool use, batch processing, and all Claude API features.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Prompt caching optimization", "Model version migration", "Tool use implementation", "Batch processing", "Streaming support", "SDK debugging"]),
        "install_instructions": "Built-in skill. Invoke with /claude-api",
        "popularity_score": 8.8,
        "tags": ["api", "claude-code", "anthropic", "sdk", "llm", "integration"],
    },
    {
        "name": "keybindings-help",
        "description": "Customize keyboard shortcuts, rebind keys, add chord bindings, or modify keybindings.json. Makes Claude Code more ergonomic with custom key mappings.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Custom keybinding creation", "Chord shortcut support", "keybindings.json management", "Key remapping", "Ergonomic customization"]),
        "install_instructions": "Built-in skill. Invoke with /keybindings-help",
        "popularity_score": 6.5,
        "tags": ["keybindings", "claude-code", "customization", "shortcuts", "ux"],
    },
    {
        "name": "loop",
        "description": "Run a prompt or slash command on a recurring interval. Set up recurring tasks, poll for status, or run something repeatedly on an interval like checking deploys every 5 minutes.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Interval-based execution", "Command scheduling", "Deploy monitoring", "Status polling", "Recurring task automation"]),
        "install_instructions": "Built-in skill. Invoke with /loop 5m /command",
        "popularity_score": 7.2,
        "tags": ["scheduling", "claude-code", "automation", "monitoring", "recurring"],
    },
    {
        "name": "fewer-permission-prompts",
        "description": "Scan transcripts for common read-only Bash and MCP tool calls, then add a prioritized allowlist to project settings.json to reduce permission prompts during Claude Code sessions.",
        "category": "Claude Code Skill",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic Claude Code",
        "pricing": "free",
        "features": json.dumps(["Transcript analysis", "Allowlist generation", "Permission optimization", "settings.json update", "UX improvement"]),
        "install_instructions": "Built-in skill. Invoke with /fewer-permission-prompts",
        "popularity_score": 7.8,
        "tags": ["permissions", "claude-code", "configuration", "ux", "optimization"],
    },

    # === MCP Servers ===
    {
        "name": "filesystem MCP",
        "description": "MCP server for local filesystem access. Allows Claude to read, write, and manage files and directories on your local machine with configurable permissions and root path restrictions.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["Read/write files", "Directory listing", "File search", "Configurable root paths", "Permission controls"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-filesystem",
        "popularity_score": 9.0,
        "tags": ["mcp", "filesystem", "file-management", "local", "official"],
    },
    {
        "name": "github MCP",
        "description": "MCP server for GitHub integration. Enables Claude to interact with GitHub repositories, issues, pull requests, commits, and more through the GitHub API.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["Repository management", "Issues and PRs", "Code search", "File contents", "Branch management", "Commit history"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-github\nRequires GITHUB_PERSONAL_ACCESS_TOKEN env var.",
        "popularity_score": 9.2,
        "tags": ["mcp", "github", "git", "version-control", "official", "devops"],
    },
    {
        "name": "postgres MCP",
        "description": "MCP server for PostgreSQL database access. Allows Claude to query, inspect schemas, and interact with PostgreSQL databases with read-only mode support for safety.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["SQL query execution", "Schema inspection", "Table listing", "Read-only mode support", "Connection pooling"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-postgres\nRequires PostgreSQL connection string.",
        "popularity_score": 8.5,
        "tags": ["mcp", "database", "postgresql", "sql", "official", "data"],
    },
    {
        "name": "puppeteer MCP",
        "description": "MCP server that provides browser automation via Puppeteer. Enables web scraping, screenshot capture, form filling, and automated browser interactions for testing and research.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["Web page navigation", "Screenshot capture", "Form automation", "JavaScript execution", "Web scraping", "Click and type simulation"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-puppeteer",
        "popularity_score": 8.8,
        "tags": ["mcp", "browser", "automation", "scraping", "official", "puppeteer"],
    },
    {
        "name": "brave-search MCP",
        "description": "MCP server for Brave Search API integration. Provides web and news search capabilities using Brave's privacy-focused search engine with rich result metadata.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
        "source_name": "MCP Official",
        "pricing": "freemium",
        "price_details": "Free tier: 2000 queries/month. Pro plan available for higher volume.",
        "features": json.dumps(["Web search", "News search", "Privacy-focused results", "Rich metadata", "Image search"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-brave-search\nRequires BRAVE_API_KEY env var.",
        "popularity_score": 8.7,
        "tags": ["mcp", "search", "brave", "web-search", "official", "privacy"],
    },
    {
        "name": "fetch MCP",
        "description": "MCP server for HTTP fetching. Allows Claude to fetch web pages, APIs, and resources with full request/response control including custom headers and authentication.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["HTTP/HTTPS requests", "Custom headers", "Authentication support", "JSON parsing", "HTML content extraction", "Robots.txt compliance"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-fetch",
        "popularity_score": 9.1,
        "tags": ["mcp", "http", "web", "api", "official", "networking"],
    },
    {
        "name": "memory MCP",
        "description": "MCP server providing persistent memory via a knowledge graph. Allows Claude to store, retrieve, and reason over facts across conversations using an entity-relation model.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["Persistent knowledge graph", "Entity creation and linking", "Relation management", "Cross-session memory", "Observation storage", "Graph queries"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-memory",
        "popularity_score": 8.6,
        "tags": ["mcp", "memory", "knowledge-graph", "persistence", "official", "ai"],
    },
    {
        "name": "everything MCP",
        "description": "A reference MCP server that demonstrates all MCP protocol features including resources, tools, prompts, and sampling. Great for testing MCP integrations and learning the protocol.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["All MCP primitives", "Resource demonstration", "Tool examples", "Prompt templates", "Sampling reference", "Testing utility"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-everything",
        "popularity_score": 6.5,
        "tags": ["mcp", "reference", "testing", "official", "development"],
    },
    {
        "name": "sequential-thinking MCP",
        "description": "MCP server that enables dynamic and reflective problem-solving through sequential thought chains. Helps break complex problems into step-by-step reasoning processes with revision support.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["Step-by-step reasoning", "Thought revision support", "Branching reasoning", "Problem decomposition", "Chain-of-thought enhancement"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-sequentialthinking",
        "popularity_score": 8.2,
        "tags": ["mcp", "reasoning", "chain-of-thought", "official", "ai", "thinking"],
    },
    {
        "name": "slack MCP",
        "description": "MCP server for Slack integration. Allows Claude to read channels, post messages, search messages, and interact with Slack workspaces through the official Slack API.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
        "source_name": "MCP Official",
        "pricing": "free",
        "features": json.dumps(["Channel reading", "Message posting", "Message search", "User listing", "Thread replies", "File sharing"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-slack\nRequires SLACK_BOT_TOKEN and SLACK_TEAM_ID.",
        "popularity_score": 8.0,
        "tags": ["mcp", "slack", "messaging", "communication", "official", "workspace"],
    },
    {
        "name": "google-maps MCP",
        "description": "MCP server for Google Maps integration. Provides geocoding, place search, directions, and mapping capabilities through the Google Maps Platform API.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps",
        "source_name": "MCP Official",
        "pricing": "freemium",
        "price_details": "Requires Google Maps API key. Free tier: $200/month credit.",
        "features": json.dumps(["Geocoding", "Place search", "Directions", "Distance matrix", "Elevation data", "Time zone info"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-google-maps\nRequires GOOGLE_MAPS_API_KEY env var.",
        "popularity_score": 7.5,
        "tags": ["mcp", "maps", "geocoding", "location", "official", "google"],
    },
    {
        "name": "aws-kb-retrieval MCP",
        "description": "MCP server for AWS Knowledge Base retrieval using Bedrock Agent Runtime. Enables RAG-powered document retrieval from AWS Bedrock Knowledge Bases with semantic search.",
        "category": "MCP Server",
        "source_url": "https://github.com/modelcontextprotocol/servers/tree/main/src/aws-kb-retrieval-server",
        "source_name": "MCP Official",
        "pricing": "paid",
        "price_details": "Requires AWS account. Pay-per-use via AWS Bedrock pricing.",
        "features": json.dumps(["RAG retrieval", "AWS Bedrock integration", "Knowledge base querying", "Semantic search", "Document chunking"]),
        "install_instructions": "npm install -g @modelcontextprotocol/server-aws-kb-retrieval\nRequires AWS credentials and Knowledge Base ID.",
        "popularity_score": 7.0,
        "tags": ["mcp", "aws", "rag", "knowledge-base", "official", "bedrock", "retrieval"],
    },

    # === AI Coding Tools ===
    {
        "name": "GitHub Copilot",
        "description": "AI pair programmer by GitHub and OpenAI that offers real-time code suggestions, whole-function completions, and an integrated chat for code explanation and generation in your IDE.",
        "category": "AI Coding Tool",
        "source_url": "https://github.com/features/copilot",
        "source_name": "GitHub",
        "pricing": "paid",
        "price_details": "Individual: $10/month or $100/year. Business: $19/user/month. Free for verified students and open source maintainers.",
        "features": json.dumps(["Inline code completion", "Multi-line function generation", "Chat interface", "CLI support", "PR summarization", "Test generation", "Code explanation", "Multi-language support"]),
        "install_instructions": "Install the GitHub Copilot extension in VS Code, JetBrains, Neovim, or other supported IDEs. Sign in with your GitHub account.",
        "popularity_score": 9.9,
        "tags": ["ai-coding", "github", "openai", "ide", "autocomplete", "pair-programming"],
    },
    {
        "name": "Cursor",
        "description": "AI-first code editor built on VS Code that features deep codebase understanding, multi-file editing with Composer, natural language code generation, and powerful AI chat with codebase context.",
        "category": "AI Coding Tool",
        "source_url": "https://cursor.sh",
        "source_name": "Anysphere",
        "pricing": "freemium",
        "price_details": "Free: 2000 completions + 50 slow requests/month. Pro: $20/month. Business: $40/user/month.",
        "features": json.dumps(["Codebase-aware chat", "Composer (multi-file editing)", "Tab autocomplete", "Terminal integration", "Cursor Rules", "@codebase context", "Image upload support", "Privacy mode"]),
        "install_instructions": "Download from cursor.sh. Available for macOS, Windows, and Linux.",
        "popularity_score": 9.7,
        "tags": ["ai-coding", "editor", "vscode", "autocomplete", "chat", "multi-file"],
    },
    {
        "name": "Continue.dev",
        "description": "Open-source AI code assistant that works in VS Code and JetBrains. Supports any LLM (Claude, GPT-4, local models) with inline editing, chat, and context providers for codebase understanding.",
        "category": "AI Coding Tool",
        "source_url": "https://continue.dev",
        "source_name": "Continue",
        "pricing": "free",
        "features": json.dumps(["Open source", "Any LLM support", "Inline code editing", "Chat interface", "Context providers", "Tab autocomplete", "Custom slash commands", "Local model support"]),
        "install_instructions": "Install the Continue extension from VS Code or JetBrains marketplace. Configure your preferred LLM in config.json.",
        "popularity_score": 8.5,
        "tags": ["ai-coding", "open-source", "vscode", "jetbrains", "local-llm", "customizable"],
    },
    {
        "name": "Codeium",
        "description": "Free AI coding assistant offering intelligent code completion, chat, and search across 70+ programming languages. Works in 40+ IDEs with lightning-fast suggestions.",
        "category": "AI Coding Tool",
        "source_url": "https://codeium.com",
        "source_name": "Exafunction",
        "pricing": "freemium",
        "price_details": "Free for individuals. Teams and Enterprise plans available.",
        "features": json.dumps(["70+ language support", "40+ IDE support", "Code completion", "Chat interface", "In-context search", "Test generation", "Docstring generation", "Refactoring"]),
        "install_instructions": "Install the Codeium extension for your IDE and create a free account at codeium.com.",
        "popularity_score": 8.3,
        "tags": ["ai-coding", "free", "autocomplete", "multi-language", "ide"],
    },
    {
        "name": "Tabnine",
        "description": "AI code completion tool with privacy-first approach. Offers whole-line and full-function completions, team-trained models, and runs locally for maximum privacy and security compliance.",
        "category": "AI Coding Tool",
        "source_url": "https://tabnine.com",
        "source_name": "Tabnine",
        "pricing": "freemium",
        "price_details": "Free basic plan. Pro: $12/month. Enterprise: custom pricing.",
        "features": json.dumps(["Privacy-first (local model option)", "Team-trained models", "Whole-line completion", "Full-function completion", "30+ language support", "Self-hosted option"]),
        "install_instructions": "Install the Tabnine plugin for your IDE from the marketplace or tabnine.com.",
        "popularity_score": 8.0,
        "tags": ["ai-coding", "privacy", "autocomplete", "self-hosted", "enterprise"],
    },
    {
        "name": "Sourcegraph Cody",
        "description": "AI coding assistant with deep codebase understanding powered by Sourcegraph's code intelligence. Uses your entire codebase as context for accurate, project-specific suggestions.",
        "category": "AI Coding Tool",
        "source_url": "https://sourcegraph.com/cody",
        "source_name": "Sourcegraph",
        "pricing": "freemium",
        "price_details": "Free for individuals. Pro: $9/month. Enterprise: custom.",
        "features": json.dumps(["Full codebase context", "Multi-model support", "Code explanation", "Chat interface", "Inline editing", "Test generation", "Code search integration", "Self-hosted option"]),
        "install_instructions": "Install Cody extension for VS Code or JetBrains. Sign in with Sourcegraph account.",
        "popularity_score": 8.2,
        "tags": ["ai-coding", "codebase-search", "context-aware", "enterprise", "self-hosted"],
    },
    {
        "name": "Amazon CodeWhisperer",
        "description": "AWS's AI coding companion that generates code and suggests entire functions based on comments and existing code. Includes security scanning and AWS service integration.",
        "category": "AI Coding Tool",
        "source_url": "https://aws.amazon.com/codewhisperer",
        "source_name": "Amazon Web Services",
        "pricing": "freemium",
        "price_details": "Individual tier: free. Professional: $19/user/month.",
        "features": json.dumps(["Code generation from comments", "Security vulnerability scanning", "AWS service awareness", "15+ languages", "License tracking", "Reference tracking", "CLI support"]),
        "install_instructions": "Install the AWS Toolkit extension or CodeWhisperer plugin for your IDE. Sign in with AWS Builder ID.",
        "popularity_score": 8.1,
        "tags": ["ai-coding", "aws", "security-scanning", "autocomplete", "cloud"],
    },
    {
        "name": "Replit AI",
        "description": "AI assistant integrated into the Replit online IDE. Provides code generation, explanation, debugging, and complete projects from natural language descriptions in the browser.",
        "category": "AI Coding Tool",
        "source_url": "https://replit.com/ai",
        "source_name": "Replit",
        "pricing": "freemium",
        "price_details": "Free tier available. Core plan: $20/month includes full AI features.",
        "features": json.dumps(["Browser-based coding", "Full project generation", "Code explanation", "Debugging assistance", "Deployment integration", "50+ language support", "Collaborative editing"]),
        "install_instructions": "Access directly at replit.com. No installation required. AI features available to all users.",
        "popularity_score": 8.4,
        "tags": ["ai-coding", "browser", "no-install", "beginner-friendly", "collaborative"],
    },

    # === AI Productivity and Research Tools ===
    {
        "name": "Perplexity",
        "description": "AI-powered answer engine that searches the web in real-time to provide cited, up-to-date answers. Offers deep research mode, follow-up questions, and multi-modal search.",
        "category": "AI Productivity Tool",
        "source_url": "https://perplexity.ai",
        "source_name": "Perplexity AI",
        "pricing": "freemium",
        "price_details": "Free: standard search. Pro: $20/month includes deeper research, more models, and API access.",
        "features": json.dumps(["Real-time web search", "Source citations", "Deep research mode", "Follow-up questions", "Image search", "File upload analysis", "API access", "Multi-model (GPT-4, Claude, etc.)"]),
        "install_instructions": "Access at perplexity.ai or install the mobile app. No setup required.",
        "popularity_score": 9.4,
        "tags": ["research", "search", "ai", "citations", "web-search", "productivity"],
    },
    {
        "name": "You.com",
        "description": "Privacy-focused AI search engine combining web search with AI capabilities. Offers multiple AI modes including Smart, Genius (GPT-4/Claude), Research, and Create modes.",
        "category": "AI Productivity Tool",
        "source_url": "https://you.com",
        "source_name": "You.com",
        "pricing": "freemium",
        "price_details": "Free: basic AI search. YouPro: $15/month for advanced models and more queries.",
        "features": json.dumps(["Privacy-first search", "Multiple AI modes", "Code generation", "Image creation", "Web summarization", "App integrations", "No tracking"]),
        "install_instructions": "Access at you.com. Optional browser extension available.",
        "popularity_score": 7.8,
        "tags": ["search", "privacy", "ai", "research", "productivity"],
    },
    {
        "name": "Phind",
        "description": "AI search engine specifically designed for developers. Searches technical documentation, Stack Overflow, GitHub, and the web to provide code-focused, accurate technical answers.",
        "category": "AI Productivity Tool",
        "source_url": "https://phind.com",
        "source_name": "Phind",
        "pricing": "freemium",
        "price_details": "Free: 10 fast searches/day. Pro: $20/month for unlimited fast searches.",
        "features": json.dumps(["Developer-focused search", "Technical documentation search", "Code examples", "Multi-source aggregation", "VS Code extension", "Pair programming mode"]),
        "install_instructions": "Access at phind.com or install the VS Code extension.",
        "popularity_score": 8.6,
        "tags": ["search", "developer", "technical", "documentation", "coding", "ai"],
    },
    {
        "name": "Bing Copilot",
        "description": "Microsoft's AI assistant integrated into Bing search, Edge browser, and Windows. Powered by GPT-4 and offers creative writing, code generation, web grounding, and image generation.",
        "category": "AI Productivity Tool",
        "source_url": "https://copilot.microsoft.com",
        "source_name": "Microsoft",
        "pricing": "freemium",
        "price_details": "Free: unlimited basic access. Copilot Pro: $20/month for priority access and more features.",
        "features": json.dumps(["GPT-4 powered", "Web grounding", "Image generation (DALL-E)", "Code generation", "Document analysis", "Edge browser integration", "Windows integration"]),
        "install_instructions": "Access at copilot.microsoft.com or use in Microsoft Edge browser.",
        "popularity_score": 8.5,
        "tags": ["ai", "microsoft", "search", "gpt-4", "image-generation", "productivity"],
    },
    {
        "name": "ChatGPT plugins",
        "description": "OpenAI's plugin ecosystem for ChatGPT that allows connecting to external services and APIs. Includes plugins for web browsing, code execution, data analysis, and hundreds of third-party integrations.",
        "category": "AI Productivity Tool",
        "source_url": "https://openai.com/chatgpt",
        "source_name": "OpenAI",
        "pricing": "paid",
        "price_details": "Requires ChatGPT Plus ($20/month) to access plugins and advanced tools.",
        "features": json.dumps(["Web browsing", "Code interpreter (Python)", "DALL-E image generation", "Data analysis", "File upload/analysis", "300+ third-party plugins", "API actions"]),
        "install_instructions": "Sign up for ChatGPT Plus at chat.openai.com. Enable desired plugins in settings.",
        "popularity_score": 9.2,
        "tags": ["ai", "openai", "plugins", "chatgpt", "gpt-4", "data-analysis", "code-execution"],
    },
    {
        "name": "NotebookLM",
        "description": "Google's AI research assistant that works with your documents. Upload PDFs, Google Docs, and websites to get AI-powered summaries, Q&A, and synthesis of your personal knowledge base.",
        "category": "AI Productivity Tool",
        "source_url": "https://notebooklm.google.com",
        "source_name": "Google",
        "pricing": "free",
        "features": json.dumps(["Document Q&A", "PDF analysis", "Source grounding", "Summary generation", "Research synthesis", "Audio overview generation", "Multi-source analysis", "Citation tracking"]),
        "install_instructions": "Access at notebooklm.google.com with a Google account.",
        "popularity_score": 8.9,
        "tags": ["research", "documents", "ai", "google", "knowledge-base", "pdf", "rag"],
    },
    {
        "name": "Windsurf",
        "description": "AI-powered IDE by Codeium featuring the Cascade AI system. Offers deep codebase awareness, autonomous multi-file editing, browser integration, and terminal command execution.",
        "category": "AI Coding Tool",
        "source_url": "https://codeium.com/windsurf",
        "source_name": "Codeium",
        "pricing": "freemium",
        "price_details": "Free tier with limited credits. Pro: $15/month.",
        "features": json.dumps(["Cascade AI agent", "Multi-file autonomous editing", "Browser integration", "Terminal execution", "Deep codebase indexing", "Inline editing", "Chat interface"]),
        "install_instructions": "Download Windsurf from codeium.com/windsurf. Available for macOS, Windows, and Linux.",
        "popularity_score": 9.0,
        "tags": ["ai-coding", "ide", "autonomous", "multi-file", "agent", "codeium"],
    },
    {
        "name": "Aider",
        "description": "AI pair programming tool in your terminal. Works with git to make changes across your codebase based on natural language instructions, with auto-commit and multi-model support.",
        "category": "AI Coding Tool",
        "source_url": "https://aider.chat",
        "source_name": "Aider",
        "pricing": "free",
        "features": json.dumps(["Terminal-based", "Git auto-commit", "Multi-model (GPT-4, Claude, Gemini)", "Multi-file editing", "Repo map", "Linting integration", "Voice coding"]),
        "install_instructions": "pip install aider-chat\naider --model gpt-4o (or your preferred model)",
        "popularity_score": 8.7,
        "tags": ["ai-coding", "terminal", "git", "open-source", "multi-model", "cli"],
    },
    {
        "name": "v0 by Vercel",
        "description": "Vercel's AI tool for generating React/Next.js UI components from text descriptions. Produces clean, Shadcn/Tailwind-based components that can be copied directly into projects.",
        "category": "AI Coding Tool",
        "source_url": "https://v0.dev",
        "source_name": "Vercel",
        "pricing": "freemium",
        "price_details": "Free: limited generations/month. Pro plans available.",
        "features": json.dumps(["React component generation", "Shadcn UI integration", "TailwindCSS output", "Live preview", "Iterative refinement", "Next.js optimization", "Copy-paste workflow"]),
        "install_instructions": "Access at v0.dev with a Vercel account.",
        "popularity_score": 8.8,
        "tags": ["ai-coding", "react", "ui", "tailwind", "vercel", "components", "frontend"],
    },
    {
        "name": "Claude.ai",
        "description": "Anthropic's conversational AI assistant. Excels at coding, writing, analysis, research, and complex reasoning. Available via web, mobile, and API with document upload capabilities.",
        "category": "AI Productivity Tool",
        "source_url": "https://claude.ai",
        "source_name": "Anthropic",
        "pricing": "freemium",
        "price_details": "Free: Claude 3 Haiku access. Pro: $20/month for Claude 3.5 Sonnet/Opus, higher limits, Projects.",
        "features": json.dumps(["Advanced reasoning", "Code generation", "Document analysis", "Long context (200K tokens)", "Projects feature", "Artifacts (runnable code)", "Voice mode", "Mobile app"]),
        "install_instructions": "Access at claude.ai or download the mobile app. API access via api.anthropic.com.",
        "popularity_score": 9.8,
        "tags": ["ai", "anthropic", "coding", "writing", "analysis", "reasoning", "llm"],
    },
    {
        "name": "Devin",
        "description": "Cognition's autonomous AI software engineer capable of planning and executing complex engineering tasks end-to-end. Can set up environments, write code, run tests, and deploy applications.",
        "category": "AI Coding Tool",
        "source_url": "https://cognition.ai",
        "source_name": "Cognition AI",
        "pricing": "paid",
        "price_details": "Teams plan: $500/month for 250 ACUs. Enterprise: custom pricing.",
        "features": json.dumps(["Autonomous coding agent", "End-to-end task execution", "Environment setup", "Multi-step planning", "Web browsing", "Terminal access", "Git integration", "Bug fixing"]),
        "install_instructions": "Request access at cognition.ai. Access provided via web interface.",
        "popularity_score": 8.5,
        "tags": ["ai-agent", "autonomous", "software-engineering", "devops", "full-stack"],
    },
    {
        "name": "Bolt.new",
        "description": "StackBlitz's AI-powered full-stack web development environment. Generate, edit, and deploy complete web applications from natural language prompts directly in the browser.",
        "category": "AI Coding Tool",
        "source_url": "https://bolt.new",
        "source_name": "StackBlitz",
        "pricing": "freemium",
        "price_details": "Free tier with limited tokens/day. Pro plans for more usage.",
        "features": json.dumps(["Browser-based development", "Full-stack app generation", "One-click deployment", "Live preview", "npm package support", "Git integration", "Claude/GPT-4 powered"]),
        "install_instructions": "Access at bolt.new. No installation required.",
        "popularity_score": 8.9,
        "tags": ["ai-coding", "browser", "full-stack", "deployment", "no-install", "react"],
    },
    {
        "name": "Lovable",
        "description": "AI full-stack engineer that builds and deploys web applications from natural language descriptions. Generates React/Supabase apps with real-time preview and GitHub sync.",
        "category": "AI Coding Tool",
        "source_url": "https://lovable.dev",
        "source_name": "Lovable",
        "pricing": "freemium",
        "price_details": "Free: 5 projects. Pro: $20/month.",
        "features": json.dumps(["Natural language to app", "React generation", "Supabase integration", "Real-time preview", "GitHub sync", "Custom domain deployment", "Team collaboration"]),
        "install_instructions": "Access at lovable.dev with a GitHub account.",
        "popularity_score": 8.6,
        "tags": ["ai-coding", "full-stack", "react", "supabase", "deployment", "no-code"],
    },
    {
        "name": "Claude Code CLI",
        "description": "Anthropic's agentic AI coding tool that runs in the terminal with full codebase context. Reads, writes, and runs code across your entire project, integrates with git, supports MCP servers, and executes multi-step tasks autonomously.",
        "category": "AI Coding Tool",
        "source_url": "https://claude.ai/code",
        "source_name": "Anthropic",
        "pricing": "freemium",
        "price_details": "Requires Anthropic API key (pay-per-token) or Claude Pro/Max subscription ($20–$100/month). Free tier available via API.",
        "features": json.dumps([
            "Full codebase context",
            "Multi-file autonomous editing",
            "Terminal & shell command execution",
            "Git integration (commit, push, PR creation)",
            "MCP server support",
            "Built-in skills system (/deep-research, /review, etc.)",
            "Web interface + VS Code / JetBrains extensions",
            "Agent SDK for custom agents",
            "Parallel subagents",
            "Claude Opus 4 / Sonnet powered"
        ]),
        "install_instructions": "npm install -g @anthropic-ai/claude-code\nOr via the Claude.ai web interface at claude.ai/code",
        "popularity_score": 9.9,
        "tags": ["ai-coding", "anthropic", "terminal", "cli", "agent", "git", "mcp", "autonomous", "agentic"],
    },
]


async def seed_data(db: aiosqlite.Connection):
    """Seed the database with initial skill data if it's empty."""
    async with db.execute("SELECT COUNT(*) as cnt FROM skills") as cursor:
        row = await cursor.fetchone()
        if row and row["cnt"] > 0:
            return  # Already seeded

    print(f"Seeding database with {len(SEED_SKILLS)} skills...")

    for skill_data in SEED_SKILLS:
        tags = skill_data.pop("tags", [])
        now = datetime.utcnow().isoformat()

        try:
            cursor = await db.execute(
                """INSERT INTO skills (name, description, category, source_url, source_name,
                   pricing, price_details, features, install_instructions, version,
                   popularity_score, last_checked, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    skill_data.get("name", ""),
                    skill_data.get("description", ""),
                    skill_data.get("category", ""),
                    skill_data.get("source_url", ""),
                    skill_data.get("source_name", ""),
                    skill_data.get("pricing", "free"),
                    skill_data.get("price_details", ""),
                    skill_data.get("features", "[]"),
                    skill_data.get("install_instructions", ""),
                    skill_data.get("version", ""),
                    skill_data.get("popularity_score", 0.0),
                    now,
                    now,
                    now,
                )
            )
            skill_id = cursor.lastrowid

            for tag_name in tags:
                tag_name = tag_name.strip().lower()
                if not tag_name:
                    continue
                async with db.execute(
                    "SELECT id FROM tags WHERE name = ?", (tag_name,)
                ) as tag_cursor:
                    tag_row = await tag_cursor.fetchone()
                if tag_row:
                    tag_id = tag_row["id"]
                else:
                    tag_cursor = await db.execute(
                        "INSERT INTO tags (name) VALUES (?)", (tag_name,)
                    )
                    tag_id = tag_cursor.lastrowid

                await db.execute(
                    "INSERT OR IGNORE INTO skill_tags (skill_id, tag_id) VALUES (?, ?)",
                    (skill_id, tag_id)
                )

        except Exception as e:
            print(f"Error seeding skill {skill_data.get('name', 'unknown')}: {e}")

    await db.commit()
    print("Database seeding complete.")

    # Add some skill combinations
    await _seed_combinations(db)


async def _seed_combinations(db: aiosqlite.Connection):
    """Add known useful skill combinations."""
    combinations = [
        ("GitHub Copilot", "code-review", "AI-Assisted PR Review",
         "Use GitHub Copilot to write code faster, then run /code-review to catch bugs before merging."),
        ("GitHub Copilot", "security-review", "Secure Coding Workflow",
         "Generate code with Copilot and verify security posture with /security-review."),
        ("brave-search MCP", "fetch MCP", "Comprehensive Web Research",
         "Use brave-search to find relevant pages, then fetch MCP to deep-dive into specific pages."),
        ("memory MCP", "sequential-thinking MCP", "Stateful Reasoning Agent",
         "Combine persistent memory with sequential thinking for complex multi-step tasks that need state."),
        ("github MCP", "code-review", "Automated PR Review Pipeline",
         "Use github MCP to fetch PR diffs and /code-review to analyze them automatically."),
        ("puppeteer MCP", "brave-search MCP", "Web Research Automation",
         "Search with Brave to find URLs, then use Puppeteer to extract detailed content from pages."),
        ("Cursor", "Continue.dev", "Best of Both AI Editors",
         "Use Cursor for complex multi-file tasks and Continue.dev for lightweight completions with local models."),
        ("NotebookLM", "Perplexity", "Deep Research Stack",
         "Use Perplexity to find sources online, then upload them to NotebookLM for deeper analysis."),
        ("Aider", "code-review", "Terminal Coding Workflow",
         "Use Aider to implement features from the terminal, then verify quality with /code-review."),
        ("filesystem MCP", "github MCP", "Local-to-Cloud Workflow",
         "Use filesystem MCP for local file operations and github MCP to push changes to GitHub."),
    ]

    for name1, name2, use_case, description in combinations:
        async with db.execute(
            "SELECT id FROM skills WHERE name = ?", (name1,)
        ) as c1:
            row1 = await c1.fetchone()
        async with db.execute(
            "SELECT id FROM skills WHERE name = ?", (name2,)
        ) as c2:
            row2 = await c2.fetchone()

        if row1 and row2:
            await db.execute(
                """INSERT OR IGNORE INTO skill_combinations (skill_id_1, skill_id_2, use_case, description)
                   VALUES (?, ?, ?, ?)""",
                (row1["id"], row2["id"], use_case, description)
            )

    await db.commit()
    print("Skill combinations seeded.")
